LOAD DATA LOCAL INFILE 'Items.dat' INTO TABLE Items
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"';
LOAD DATA LOCAL INFILE 'Users.dat' INTO TABLE Users
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"';
LOAD DATA LOCAL INFILE 'Categories.dat' INTO TABLE Categories
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"';
LOAD DATA LOCAL INFILE 'Bids.dat' INTO TABLE Bids
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"';
